version: "2"

run:
  timeout: 5m

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    #- gosimple
    - unused
  disable:
    - depguard
    #- exhaustivestruct
    - funlen
    - gochecknoglobals
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    #- goerr113
    # - gofumpt   ❌ removed
    #- goimports
    #- golint
    #- gomnd
    - gosec
    - lll
    #- maligned
    - misspell
    - nakedret
    - nestif
    - nlreturn
    - prealloc
    - predeclared
    - testpackage
    - unparam
    - whitespace
    - wrapcheck
    - wsl
