name: Go Lint
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    paths:
      - '**.go'
jobs:
  golangci-lint:
    name: Run golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.x'

      - name: Install dependencies
        run: go mod tidy

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.61.0  # latest stable version as of Oct 2025
          args: --timeout=5m
